# Generated by Django 5.1.1 on 2024-10-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedurePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_quantity', models.IntegerField(default=0)),
                ('end_quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Procedure Price',
                'verbose_name_plural': 'Procedure Prices',
                'db_table': 'procedure_prices',
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Procedure Type',
                'verbose_name_plural': 'Procedure Types',
                'db_table': 'procedure_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('default', models.BooleanField(default=False)),
                ('default_quantity', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('additional_information', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Referral Person',
                'verbose_name_plural': 'Referral Persons',
                'db_table': 'referral_persons',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('number_of_recommended_treatments', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clients.client')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_procedures', to='main.department')),
                ('procedure_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_for_type', to='main.proceduretype')),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'db_table': 'procedures',
            },
        ),
        migrations.CreateModel(
            name='ProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_th_treatment', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_received', models.BooleanField(default=False)),
                ('received_dt', models.DateTimeField(blank=True, null=True)),
                ('drug', models.IntegerField(default=1, verbose_name='Giyox')),
                ('adapter', models.IntegerField(default=2, verbose_name='Nakanechnik')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.procedure')),
            ],
            options={
                'verbose_name': 'Procedure item',
                'verbose_name_plural': 'Procedure items',
                'db_table': 'procedure_items',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('procedure_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.procedureitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_expenses', to='main.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_paid', models.BooleanField(default=False)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_items', to='main.referralperson')),
            ],
            options={
                'verbose_name': 'Referral Item',
                'verbose_name_plural': 'Referral Items',
                'db_table': 'referral_items',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_method', models.CharField(choices=[('card', 'Terminal orqali.'), ('cash', 'Naqd.'), ('transfer_to_card', 'Kartadan kartaga.')], max_length=20)),
                ('transfer_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_transfers', to='main.department')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_payments', to='main.procedure')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfers',
            },
        ),
    ]
