# Generated by Django 5.1.1 on 2024-09-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('additional_information', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Referral Person',
                'verbose_name_plural': 'Referral Persons',
                'db_table': 'referral_persons',
            },
        ),
        migrations.CreateModel(
            name='ReferralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('was_paid', models.BooleanField(default=False)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_items', to='main.referralperson')),
            ],
            options={
                'verbose_name': 'Referral Item',
                'verbose_name_plural': 'Referral Items',
                'db_table': 'referral_items',
            },
        ),
    ]
