# Generated by Django 5.1.1 on 2024-09-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_referralperson_referralitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n_th_treatment', models.IntegerField(default=0)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.procedure')),
            ],
            options={
                'verbose_name': 'Procedure item',
                'verbose_name_plural': 'Procedure items',
                'db_table': 'procedure_items',
            },
        ),
    ]
