# Generated by Django 5.1.1 on 2024-09-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_procedure_description_expenseitem_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='payment_procedure',
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure_payments', to='main.procedure'),
        ),
        migrations.DeleteModel(
            name='PaymentProcedure',
        ),
    ]
