# Generated by Django 5.1.1 on 2024-10-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_transfer_payment_procedure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedurePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_quantity', models.IntegerField(default=0)),
                ('end_quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Procedure Price',
                'verbose_name_plural': 'Procedure Prices',
                'db_table': 'procedure_prices',
            },
        ),
    ]
