# Generated by Django 5.1.1 on 2024-10-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_procedureprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_method',
            field=models.CharField(choices=[('card', "Terminal orqali to'lov"), ('cash', 'Naqd'), ('transfer_to_card', "Karta orqali o'tkazma")], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=20),
        ),
    ]
