# Generated by Django 5.1.1 on 2024-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_procedure_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
