# Generated by Django 5.1.1 on 2024-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
