# Generated by Django 5.1.1 on 2024-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_default_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureitem',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='received_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_method',
            field=models.CharField(choices=[('card', 'Terminal orqali.'), ('cash', 'Naqd'), ('transfer_to_card', 'Kartadan kartaga')], max_length=20),
        ),
    ]
