# Generated by Django 5.1.1 on 2024-10-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_procedureitem_is_received_procedureitem_received_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_method',
            field=models.CharField(choices=[('card', 'Terminal orqali.'), ('cash', 'Naqd.'), ('transfer_to_card', 'Kartadan kartaga.')], max_length=20),
        ),
    ]
