# Generated by Django 5.1.1 on 2024-10-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transfer_description_alter_transfer_transfer_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_transfers', to='main.department'),
        ),
    ]
