# Generated by Django 5.1.1 on 2024-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_transfer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureitem',
            name='adapter',
            field=models.IntegerField(default=1, verbose_name='Nakanechnik'),
        ),
        migrations.AddField(
            model_name='procedureitem',
            name='drug',
            field=models.IntegerField(default=1, verbose_name='Giyox'),
        ),
    ]
