# Generated by Django 5.1.1 on 2024-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_procedureitem_adapter_procedureitem_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureitem',
            name='adapter',
            field=models.IntegerField(default=2, verbose_name='Nakanechnik'),
        ),
    ]
