services:
  postgres_base:
    build:
      context: .
      dockerfile: ./etc/compose/postgres/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-food_delivery}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-food_delivery}
      POSTGRES_DB: ${POSTGRES_DB:-food_delivery}
    volumes:
      - ./mounts/postgres/pg_data:/var/lib/postgresql/data
      - ./mounts/postgres/backups:/backups
      - ./mounts/postgres/logs:/var/log/postgresql
    #      - ./etc/compose/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    stdin_open: true
    tty: true
  django_base:
    build:
      context: .
      dockerfile: etc/compose/django/Dockerfile
    command: >
      sh -c  "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn 
      --reload"
    restart: unless-stopped
    volumes:
      - ./django:/django
      - ./mounts/django/logs:/django/logs
      - ./mounts/django/static:/django/static
      - ./mounts/django/media:/django/media
    stdin_open: true
    tty: true

  nginx_base:
    build:
      context: .
      dockerfile: ./etc/compose/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./mounts/nginx/logs:/var/log/nginx
      - ./mounts/django/static:/var/www/html/static:ro
      - ./mounts/django/media:/var/www/html/media:ro
      - ./etc/compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    tty: true

  celery_worker_base:
    build:
      context: .
      dockerfile: etc/compose/django/Dockerfile
    image: celery_worker
    restart: unless-stopped
    command: celery -A conf worker -l info --autoscale 3,1
    env_file:
      - .env
    volumes:
      - ./django:/django
      - ./mounts/django/logs:/django/logs
      - ./mounts/django/static:/django/static
      - ./mounts/django/media:/django/media
    depends_on:
      - redis
      - django

  celery_beat_base:
    build:
      context: .
      dockerfile: etc/compose/django/Dockerfile
    image: celery_beat
    restart: unless-stopped
    command: celery -A conf beat -l info
    env_file:
      - .env
    volumes:
      - ./django:/django
      - ./mounts/django/logs:/django/logs
      - ./mounts/django/static:/django/static
      - ./mounts/django/media:/django/media
    depends_on:
      - redis
      - django

  flower_base:
    build:
      context: .
      dockerfile: etc/compose/django/Dockerfile
    image: mher/flower
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A conf flower --conf=flower.conf.py --port=5555
    volumes:
      - ./django:/django
      - ./mounts/django/logs:/django/logs
    depends_on:
      - redis
      - django
      - celery_worker

  redis_base:
    image: redis:6.2.1
    restart: unless-stopped
    privileged: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mounts/redis_data:/data
      - ./mounts/redis_conf:/conf
    ports:
      - :6379
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    stdin_open: true
    tty: true
