# Generated by Django 5.1.1 on 2024-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='client',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
