# Generated by Django 5.1.1 on 2024-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_address_client_diagnosis_client_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
