#name: Deploy to server
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.3
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}
#
#      - name: Deploy to Server
#        run: |
#          ssh -o StrictHostKeyChecking=no auto_poster@185.43.6.212 'cd ~/el-xizmati; docker compose down ; git pull ; docker compose up -d --build'
